### ISSUE TITLE
Onlyoffice doesn't work with Traefik reverse proxy

### ISSUE THREAD

**Issue by ADIX7** [mickael-kerjean/filestash#355]
I set up Filestash with Onlyoffice it does work correctly without Traefik. With Traefik Filestash still works correctly but Onlyoffice throws an "Unknown error" after the initial UI load.

I tried set `transport.respondingTimeouts.readTimeout` which is the closest equivalent of `proxy_read_timeout`,
also tried set `buffering.maxRequestBodyBytes` which corresponds to `client_max_body_size`,
and tried set `Strict-Transport-Security` to `max-age=31536000; includeSubDomains`.

**Comment by mickael-kerjean** [comment]
You can get support from [here](https://www.filestash.app/pricing/). I only use github for bug and feature request

**Comment by ADIX7** [comment]
I finally managed to make it work. For some reason traefik does nto set (?) X-Forwarded-Proto so you have to add a middleware to do that.

Here is a sample config for the middlewares:
```
http:
  middlewares:
    xfwdprotohttp:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: http
    xfwdprotohttps:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: https
```

And a sample config for docker-compose:
_(Note: The config uses entrypoints `http` and `https` that is not included in the config)_
_(Note: The https config uses a certresolver named `letsencrypt` that is not included in the config)_
```
version: "3"
services:
  filestash:
    container_name: filestash
    image: machines/filestash
    restart: always
    environment:
    - APPLICATION_URL=files.your.domain
    - ONLYOFFICE_URL=http://onlyoffice
    volumes:
      - "./data/:/app/data/state"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filestash.rule=Host(`files.your.domain`)"
      - "traefik.http.routers.filestash.entrypoints=http"
      - "traefik.http.routers.filestash.middlewares=xfwdprotohttp@file"
      - "traefik.http.routers.filestash-secure.rule=Host(`files.your.domain`)"
      - "traefik.http.routers.filestash-secure.entrypoints=https"
      - "traefik.http.routers.filestash-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.filestash-secure.middlewares=xfwdprotohttps@file"

  onlyoffice:
    container_name: onlyoffice
    image: onlyoffice/documentserver
    stdin_open: true
    restart: always
    stop_grace_period: 60s
```

_(Note: The config creates http and https endpoints too. For production http is not recommended. Remove the lines with `traefik.http.routers.filestash` and keep only the ones with `traefik.http.routers.filestash-secure`)_

@mickael-kerjean You can include these or a modified version of them in the docs if you want. The point is you have to set X-Forwarded-Proto
