### ISSUE TITLE
[bug] Local plugin: folders created with incorrect permissions

### ISSUE THREAD

**Issue by SlavikCA** [mickael-kerjean/filestash#434]
# Description of the bug

can't write files to any folders, created by "Local" plugin

# Step by step instructions to reproduce the bug

I'm running Filestash in Docker on Synology, behind Traefik
```
version: '2'
services:
  app:
    container_name: filestash
    image: machines/filestash
    mem_limit: 2G
    volumes:
      - ./data:/data
      - ./state:/app/data/state
    ports:
    - "8334:8334"
    labels:
      - traefik.enable=true
      - traefik.http.routers.filestash.rule=Host(`filestash.slavikf.com`)
    environment:
    - APPLICATION_URL=filestash.slavikf.com
```
I'm using "Local" plugin, pointed to `/data`.
for that `/data` mount I did:
```
chown 1000:1000 data
chmod 777 data
```
I can upload files - no issues.
However, if I create any folder from Filestash UI - then no files can be uploaded to that new folder, I'm getting error.

But if I `chmod 777` for the newly created folder, then upload is working for it.
