### ISSUE TITLE
[bug] Docker compose fails to start - exec format error

### ISSUE THREAD

**Issue by helblingjoel** [mickael-kerjean/filestash#513]
# Description of the bug

When trying to start the application on a Raspberry Pi 3B+ using `docker compose up` filestash and filestash_oods fail to start.

```
joel@raspberry:~/filestash$ docker compose up
[+] Running 3/3
 ⠿ Network filestash_default  Created                                                                                         3.9s
 ⠿ Container filestash_oods   Created                                                                                        17.8s
 ⠿ Container filestash        Created                                                                                         8.4s
Attaching to filestash, filestash_oods
filestash       | exec /app/filestash: exec format error
filestash_oods  | exec /app/ds/run-document-server.sh: exec format error
filestash exited with code 1
filestash_oods exited with code 0

```

# Step by step instructions to reproduce the bug

As described in the installation guide on https://www.filestash.app/docs/install-and-upgrade/
`mkdir filestash && cd filestash`

`curl -O https://downloads.filestash.app/latest/docker-compose.yml`

`docker compose up`

# Can you replicate that error from the demo?

No. Is related to startup behaviour

# Observed behavior

filestash and filestash_oods fail to start with error message `exec format error`

# Expected behavior

filestash and filestash_oods containers start up and become accessible on default ports 8334 as described in installation guide.

# Supporting evidence

docker-compose.yml

```
joel@raspberry:~/filestash$ cat docker-compose.yml 
version: '2'
services:
  app:
    container_name: filestash
    image: machines/filestash
    restart: unless-stopped
    environment:
    - ONLYOFFICE_URL=http://onlyoffice
    ports:
    - "8334:8334"

  onlyoffice:
    container_name: filestash_oods
    image: onlyoffice/documentserver
    restart: always
joel@raspberry:~/filestash$ 
```
