### ISSUE TITLE
[bug] local storage backend: quick access not syncing

### ISSUE THREAD

**Issue by sven-eliasen** [mickael-kerjean/filestash#517]
# Description of the bug

With a local storage backend and deleting a folder from outside of filestash (`rm` from terminal by example), the quick access is keeping a dangling reference to the deleted folder.

# Step by step instructions to reproduce the bug

- Setup Filestash with a binded volume to host as local storage backend.
- In Filestash, create a folder and visit it to make it appear in the quick access menu
- In your host terminal, delete the created folder in the binded volume
- Back in Filestash, F5 to see that your folder has been deleted but not in the quick access menu.

# Can you replicate that error from the demo?

I don't think so as I would need to delete a folder from outside filestash.

# Observed behavior

Deleted folder still in the quick access menu, pointing to nothing.

# Expected behavior

Deleted folder disappearing from quick access as it disappeared from the files menu.

# Other

For my usage, I actually don't need a quick access menu as folders will be often removed from outside Filestash, so it would be cool to be able to disable this feature.

# My docker compose

```
version: '2'
services:
  app:
    container_name: filestash
    image: machines/filestash
    restart: always
    user: 1000:1000
    ports:
    - "8080:8334"
    volumes:
    - /docker/filestash/data:/app/data/state
    - /uploads:/app/data/uploads
```

PS: Thanks for this awesome project.
