### ISSUE TITLE
how to deploy filestash on k8s? is there example yaml?

### ISSUE THREAD

**Issue by zhucan** [mickael-kerjean/filestash#531]
```
apiVersion: v1
kind: Service
metadata:
  name: filestash
  namespace: monitoring
  labels:
    app: filestash
spec:
  type: NodePort
  ports:
  - name: http
    port: 8334
    targetPort: 8334
    nodePort: 8334
    protocol: TCP
  selector:
    app: filestash

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filestash
  namespace: monitoring
  labels:
    app: filestash
spec:
  replicas: 2
  selector:
    matchLabels:
      app: filestash
  template:
    metadata:
      labels:
        app: filestash
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: filestash
            topologyKey: kubernetes.io/hostname
      containers:
        - image: machines/filestash
          name: filestash
          ports:
            - containerPort: 8334
          imagePullPolicy: IfNotPresent

```
