### ISSUE TITLE
[bug] Middleware configuration is lost upon restart

### ISSUE THREAD

**Issue by Haarolean** [mickael-kerjean/filestash#564]
# Description of the bug

Upon a restart my middleware configuration (passthrough for S3) is being lost like it's never been there.

# Step by step instructions to reproduce the bug

1. Set up the app (I use `machines/filestash` image)
`machines/filestash                        latest                  1d247ef124b3   2 months ago    1.1GB`
2. Set up s3 backend with a passthrough middleware
3. Restart the container
4. Profit

# Can you replicate that error from the demo?

# Observed behavior

settings are being lost

# Expected behavior

they're not

**Comment by Haarolean** [comment]
My container setup:
```
services:
  filestash:
    container_name: filestash
    image: machines/filestash
    restart: unless-stopped
    user: "1000:998"
    networks:
      - web_ingress
    volumes:
      - ./data:/app/data/state:rw
    environment:
      - APPLICATION_URL=https://stash.xxx.dev/
```
