### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by artem-check** [mickael-kerjean/filestash#591]
# Description of the bug

![Screenshot_2023-04-11_10-11-50](https://user-images.githubusercontent.com/1662913/231086034-164d5511-b30d-4f5d-8aac-c948fd5ff05d.png)

Onlyoffice security token error

# Step by step instructions to reproduce the bug

Clean install from the box

# Can you replicate that error from the demo?

Yes

# Observed behavior

There is an error

# Expected behavior

There is no error

**Comment by sharicov** [comment]
Have same issue connecting to windows based OnlyOffice server, is there a solution for non-docker OnlyOffice server?

**Comment by aloreaux** [comment]
I am having the same issue and cannot get onlyoffice to open. It is giving me the same error as above.

filestash docker logs: `2023/06/30 14:18:34 HTTP 200 GET    6.2ms /api/onlyoffice/iframe?path=/test.docx&share=
2023/06/30 14:21:33 HTTP 304 GET    6.4ms /api/files/ls?path=%2F
2023/06/30 14:23:42 HTTP 200 GET 5497.2ms /api/onlyoffice/iframe?path=/test.docx&share=`

filestash_oods docker logs: `[2023-06-30T14:23:44.905] [WARN] [localhost] [Xcu1bal7bOd01d3bBdFc] [userId] nodeJS - checkJwt error: name = JsonWebTokenError message = jwt malformed token = foobar`

I have tried setting multiple JWT settings, and it didn't work for any of them. Sometimes I get the token error, sometimes the JWT token, docker-compose below:

```
version: '2'

networks:
  default:
    external:
      name: nginx-network

services:
  app:
    container_name: filestash
    image: machines/filestash
    restart: always
    environment:
      - APPLICATION_URL=ftp.donnegan.com
      - ONLYOFFICE_URL=http://onlyoffice
    networks:
      - default

  onlyoffice:
    container_name: filestash_oods
    image: onlyoffice/documentserver
    restart: always
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=${OO_JWT_SECRET}
      - JWT_HEADER=AuthorizationJwt

    security_opt:
      - seccomp:unconfined
    networks:
      - default
```
