### ISSUE TITLE
[bug] can't edit storage configuration

### ISSUE THREAD

**Issue by zhqu1148980644** [mickael-kerjean/filestash#630]
# Description of the bug
1. `docker-compose up -d` the docker-compose [file](https://github.com/mickael-kerjean/filestash/blob/master/docker/docker-compose.yml) in this repo.
2. visit the admin page
3. add storage backend
4. can not edit the beckend configuration(user,pass...)

# Can you replicate that error from the demo?
no, have no access to admin page

# Observed behavior

<img width="1095" alt="image" src="https://github.com/mickael-kerjean/filestash/assets/29366130/1506dda0-a6f2-4e8f-bf63-5d692e665459">

# Expected behavior

Can edit the configuration of each storage backend

**Comment by espressoelf** [comment]
Seems to be since the rewrite of the admin control panel. In the meantime you could check `/server/plugin/plg_backend_*/index.go` for the params the backend takes before editing the configuration manually. Not the most comfortable way but it's free self-support.

**Comment by mickael-kerjean** [comment]
I can't seem to replicate this. can you replicate this in the latest version?

**Comment by espressoelf** [comment]
I just pulled the latest image and it still looks like that. Looking at the source in Developer Tools (F12) there is nothing else displayed and the console doesn't show any error. I also don't see anything looking like an error in the container's logs.

**Comment by mickael-kerjean** [comment]
I am not able to replicate this. Can you share your docker compose file and make a screenshare to see the problem in action?

**Comment by zhqu1148980644** [comment]
> I am not able to replicate this. Can you share your docker compose file and make a screenshare to see the problem in action?

The latest `docker-compose.yaml` file in this repo:
```
version: '2'
services:
  filestash:
    container_name: filestash
    image: machines/filestash
    restart: always
    environment:
    - APPLICATION_URL=
    - GDRIVE_CLIENT_ID=<gdrive_client>
    - GDRIVE_CLIENT_SECRET=<gdrive_secret>
    - DROPBOX_CLIENT_ID=<dropbox_key>
    ports:
    - "8334:8334"
    volumes:
    - filestash:/app/data/state/


volumes:
    filestash: {}
```

<img width="703" alt="image" src="https://github.com/mickael-kerjean/filestash/assets/29366130/088371ec-4cb4-4eb2-bcd9-e285d69be6ce">

**Comment by mickael-kerjean** [comment]
The image isn't enough to replicate the issue you're seeing. Can you send a video or something to show the behavior you are seeing? I really need to replicate whatever you're getting to provide a fix

**Comment by espressoelf** [comment]
I started from scratch, which means I downloaded the [docker-compose.yml](https://raw.githubusercontent.com/mickael-kerjean/filestash/master/docker/docker-compose.yml) and edited it like below:
```yaml
version: '2'
services:
  app:
    container_name: filestash2
    image: machines/filestash
    restart: always
    environment:
    - APPLICATION_URL=http://192.168.0.6:8334
#    - GDRIVE_CLIENT_ID=<gdrive_client>
#    - GDRIVE_CLIENT_SECRET=<gdrive_secret>
#    - DROPBOX_CLIENT_ID=<dropbox_key>
#    - ONLYOFFICE_URL=http://onlyoffice
    ports:
    - "8334:8334"
    volumes:
    - filestash:/app/data/state/

#  onlyoffice:
#    container_name: filestash_oods
#    image: onlyoffice/documentserver
#    restart: always
#    security_opt:
#      - seccomp:unconfined

volumes:
    filestash: {}
```

I usually use Traefik as reverse proxy, this time I didn't do that. Afterwards I pulled the latest image and made sure there is no old filestash volume. Note: I usually use directories and not volumes. 
```sh
docker pull machines/filestash # pulls :latest for amd64
docker volume rm filestash
docker-compose up
```

The server starts as usual:
```
Creating filestash2 ... done
Attaching to filestash2
filestash2 | 2023/10/20 13:08:41 SYST INFO Filestash v0.5 starting
filestash2 | 2023/10/20 13:08:41 SYST INFO [http] starting ...
filestash2 | 2023/10/20 13:08:42 SYST INFO [http] listening on :8334
```

I visit `http://192.168.0.6:8334` in the browser, set an administrator password, click away the crash report message and get the following summary:
- SSL is not configured properly: This can lead to data leaks. Please use a SSL certificate
- Application is running as 'undefined'
- Emacs is installed
- Pdftotext is installed 

Then I visit "Backend" and get the default pre-selected list of backends (WebDav, FTP, SFTP, GIT, S3, DROPBOX, GDRIVE), all with just their names configurable. Meanwhile, the log fills up with access logs. No errors or anything unusual.


Sorry it isn't a video, but I tried to be as detailed as possible while also keeping everything as untouched as possible. Is there anything special we could try?
