### ISSUE TITLE
[bug] Can't open or download files in subfolder using FTP

### ISSUE THREAD

**Issue by velicanu** [mickael-kerjean/filestash#636]
# Description of the bug

I can only open and download files from the home directory of an ftp folder. 

# Step by step instructions to reproduce the bug

Use the following docker-compose file, connect to the ftp through filestash, try to open a file in subfolder. Example in the gif below.

```
version: '2'
services:
  app:
    container_name: filestash
    image: machines/filestash
    restart: always
    # environment:
    # - APPLICATION_URL=
    # - GDRIVE_CLIENT_ID=<gdrive_client>
    # - GDRIVE_CLIENT_SECRET=<gdrive_secret>
    # - DROPBOX_CLIENT_ID=<dropbox_key>
    # - ONLYOFFICE_URL=http://onlyoffice
    ports:
    - "8334:8334"
    volumes:
    - ./state/:/app/data/state/

  onlyoffice:
    container_name: filestash_oods
    image: onlyoffice/documentserver
    restart: always
    security_opt:
      - seccomp:unconfined

  demo:
    image: delfer/alpine-ftp-server
    ports:
      - "2113:21"
    environment:
      - USERS=demo|demodemo
    container_name: demo
    restart: always
    volumes:
    - /home/ubuntu/demo/:/ftp/demo
```

# Can you replicate that error from the demo?

Cannot replicate this in the demo.

# Observed behavior

![filestash](https://github.com/mickael-kerjean/filestash/assets/5022772/1dec4701-c5b9-44b2-992a-80ec771a4589)

# Expected behavior

Subfolders to work.

**Comment by mickael-kerjean** [comment]
That's interesting, what server are you using for this? Can you send me some test credentials I could use to replicate what you're getting on your side? This is a case of a FTP server I've never seen yet, it seems that somehow you're FTP server always say everything is going well but when queries it says there's nothing in this folder.

**Comment by velicanu** [comment]
I'm using a docker based ftp server, `delfer/alpine-ftp-server` . I don't have a URL for you to test this on, but if you do `docker-compose up` with the following `docker-compose.yaml` file you should be able to reproduce this locally:

```
version: "2"
services:
  app:
    container_name: filestash
    image: machines/filestash
    restart: always
    ports:
      - "8334:8334"
    volumes:
      - ./state/:/app/data/state/

  demo:
    image: delfer/alpine-ftp-server
    environment:
      - USERS=demo|foobar
    container_name: demo
    restart: always
    volumes:
      - ./demo:/ftp/demo

```

Login credentials:
<img width="581" alt="Screenshot 2023-11-14 at 2 42 58 PM" src="https://github.com/mickael-kerjean/filestash/assets/5022772/5535e16c-09f3-4a90-b613-bf03a5395f90">
