### ISSUE TITLE
[bug] Docker container set a firewall (?) rule blocking an IP range

### ISSUE THREAD

**Issue by landure** [mickael-kerjean/filestash#703]
# Description of the bug

When starting the container, the Docker node was not accessible from my network anymore (Docker Node: 192.168.25.45 <-->router <--> 192.168.10.22 , the Docker container blocked "192.168.10.0/24" for the Docker Node).
Stopping the container reestablished the access.

The issue appeared after I tried and failed to update the secret key value with a too long value generated with `openssl rand --base64 64`

I'm not sure how to reproduce. What I don't understand is why the container would (be able to) set a firewall rule blocking a whole IP range.
The Docker node iptables command did not show the rule blocking communication.

# Step by step instructions to reproduce the bug

Start the container a first time.
Change the 

The env file is

```
# env/filestash.env
ADMIN_PASSWORD=some-passord
APPLICATION_URL=https://domain.com/
LOG_LEVEL=INFO
```

The compose file is:

```yaml
# compose.yaml
volumes:
  filestash-data:
    driver: local

networks:
  traefik:
    name: traefik-net
    external: true

services:
  filestash:
    image: machines/filestash:latest
    restart: unless-stopped
    env_file:
      - ./env/filestash.env
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - filestash-data:/app/data/state
    networks:
      default: {}
      traefik: {}
    labels:
      # Process email notifications and remove expired files.
      org.label-schema.group: web
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "true"
      traefik.exposed-by-instance: traefik-public
      traefik.http.services.securite-atelier-filebrowser-service.loadbalancer.server.port: 8334
      traefik.http.services.securite-atelier-filebrowser-service.loadbalancer.server.scheme: http
      traefik.http.routers.securite-atelier-filebrowser-https.entrypoints: websecure
      traefik.http.routers.securite-atelier-filebrowser-https.service: securite-atelier-filebrowser-service@docker
      traefik.http.routers.securite-atelier-filebrowser-https.rule: Host(`domain.com`)
      traefik.http.routers.securite-atelier-filebrowser-https.middlewares: hsts@file, security@file, compression@file
      traefik.http.routers.securite-atelier-filebrowser-https.tls: "true"
```

# Can you replicate that error from the demo?

NO

# Observed behavior

A firewall rule is set blocking an IP range (192.168.X.0/24) access to the host (no ping, no ssh, no HTTP).

# Expected behavior

The Docker container shouldn't set any firewall rule affecting the whole system.
