### ISSUE TITLE
[bug] Can't view local files on my Synology NAS

### ISSUE THREAD

**Issue by srahimeen** [mickael-kerjean/filestash#729]
# Description of the bug

I have installed filestash on my Synology DS923+ NAS using the following docker-compose.yml:

```
version: '2'
services:
  app:
    container_name: filestash
    image: machines/filestash
    restart: always
    environment:
    - APPLICATION_URL=
    - GDRIVE_CLIENT_ID=<gdrive_client>
    - GDRIVE_CLIENT_SECRET=<gdrive_secret>
    - DROPBOX_CLIENT_ID=<dropbox_key>
    - ONLYOFFICE_URL=http://onlyoffice
    ports:
    - "8334:8334"
    volumes:
    - filestash:/app/data/state/

  onlyoffice:
    container_name: filestash_oods
    image: onlyoffice/documentserver
    restart: always
    security_opt:
      - seccomp:unconfined

volumes:
    filestash: {}
```

It's running and I can access it. I have set it to only local.

![image](https://github.com/user-attachments/assets/80a5aa69-9592-41d5-9d91-81a18d259968)

When I try to view my files, I get the "Oops! Not Found" error.

![image](https://github.com/user-attachments/assets/0e19e3b7-160e-4202-986a-1d0976caba93)

What do I need to do to view my files from my NAS? I would specifically like to just view the `volume1/NAS-BACKUPS/Photos` folder from my NAS.

# Step by step instructions to reproduce the bug

1. Install filestash on Synology DS923+ NAS using above docker-compose.yml
2. Set it to only have local config as per above screenshot

# Can you replicate that error from the demo?

# Observed behavior

"Oops! Not Found" error when trying to view files.

# Expected behavior

I am able to view the local files in my Synology NAS `volume1/NAS-BACKUPS/Photos` folder
