### ISSUE TITLE
[bug] Permission related issue for config.json

### ISSUE THREAD

**Issue by xd003** [mickael-kerjean/filestash#736]
```
  filestash:
    image: machines/filestash
    container_name: filestash
    restart: unless-stopped
    expose:
      - 8334
    volumes:
      - /opt/containers/filestash:/app/data/state/
```
When deploying filestash using the docker compose. it reports about the error mentioned in the title. The real problem is that filestash container doesn't start as the user i am running the docker compose. It runs as another user which is why the permission related issue. For instance, i am runnning docker with UID/GID 1002 while filestash container runs as UID/GID 1000

**Comment by grozadanut** [comment]
I have the same permission issue as you. My problem is that I am trying to mount a local folder in the docker container using bind mounts, so I can expose it through Filestash. But filestash cannot open this folder inside the docker container, because it expects a user called filestash to own it, and there is no user filestash on the host.

As a reference, my stack is:

```
filestash:
    image: machines/filestash
    environment:
      - APPLICATION_URL=files.{{ domain }}
      - ONLYOFFICE_URL=http://onlyoffice
    volumes:
      - filestash:/app/data/state/
      - /mnt:/mnt
    networks:
      - web
      - local
    deploy:
      mode: replicated
      replicas: 1
      labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.filestash.rule=Host(`files.{{ domain }}`)"
      - "traefik.http.routers.filestash.entrypoints=websecure"
      - "traefik.http.services.filestash.loadbalancer.server.port=8334"
      - "traefik.http.routers.filestash.service=filestash"
      - "certbot.domain=files.{{ domain }}"
```
