### ISSUE TITLE
Missing documentation of config file & env vars

### ISSUE THREAD

**Issue by Chuckame** [mickael-kerjean/filestash#745]
As a new user of filestash, it's difficult to start from scratch a filestash instance with the current documentation with some pre-configured parameters (local fs, proxy auth).

It would be great to have a quick-start to deploy a filestash instance on a local bind mount, just with configuration (no magic ui), and have a documentation of this config file to allow 100% of IaC.

I've checked the documentation just giving a magic link to retrieve a really little docker-compose file, which in my opinion, lacks of trustness (I had to download, then check the downloaded file to see that there is nothing interesting except docker-compose commons like image, open port or a misterious onlyoffice, and also with some env vars to complete so that's not really magic).

Finally, as an example for my use case, I would like something like this:

### Environment variables

|env var|default|description|
|-|-|-|
|LOCAL_FS_PATH|`/mnt`|the path when local fs used|
|AUTH|noauth|Auth type. Could one of `aa`, `bb`, `proxy`|
|PROXY_AUTH_USER_HEADER|`Remote-User`|the header used for proxy auth|

### Deploy with docker compose

Deploy an instance without any configured backend:
```yaml
version: '2'
services:
  app:
    container_name: filestash
    image: machines/filestash:latest
    restart: always
    ports:
    - "8334:8334"
    volumes:
    - filestash:/app/data/state/

volumes:
    filestash: {}
```
